apiVersion: v1
kind: Service
metadata:
  name: dep-spring-load2
  namespace: default
spec:
  selector:
    app: deployment-spring
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     protocol: TCP  # optional protocol


     #Finns ingen loadblancer i minikube containern detta kommeri nte funka.